#!/usr/bin/env bash
set -euo pipefail

UNIT_NAME="${OPENCLAW_SYSTEMD_UNIT:-}"
PROFILE="${OPENCLAW_PROFILE:-}"
USER_SYSTEMD_DIR="${XDG_CONFIG_HOME:-${HOME}/.config}/systemd/user"
RELOAD_SYSTEMD=1
RESTART_SERVICE=1

log() {
  printf '==> %s\n' "$1"
}

die() {
  printf 'Error: %s\n' "$1" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "$1 is required"
}

usage() {
  cat <<'EOF'
Usage: Apply-OpenClawSystemdHardening.sh [options]

Options:
  --unit-name <name>         Override the OpenClaw systemd user unit name
  --profile <name>           OpenClaw profile name used for unit resolution
  --user-systemd-dir <path>  Override the systemd user unit directory
  --no-reload                Do not run systemctl --user daemon-reload
  --no-restart               Do not restart the service after writing the override
EOF
}

normalize_unit_name() {
  local raw="$1"
  raw="${raw%.service}"
  printf '%s' "${raw}"
}

resolve_default_unit_name() {
  local profile_name="${1:-}"
  if [[ -n "${profile_name}" && "${profile_name}" != "default" ]]; then
    printf 'openclaw-gateway-%s' "${profile_name}"
  else
    printf 'openclaw-gateway'
  fi
}

resolve_existing_unit_name() {
  local candidate
  local candidates=()

  if [[ -n "${UNIT_NAME}" ]]; then
    candidates+=("$(normalize_unit_name "${UNIT_NAME}")")
  fi

  if [[ -n "${PROFILE}" ]]; then
    candidates+=("$(resolve_default_unit_name "${PROFILE}")")
  fi

  candidates+=("$(resolve_default_unit_name "")")
  candidates+=("clawdbot-gateway")
  candidates+=("moltbot-gateway")

  for candidate in "${candidates[@]}"; do
    if [[ -f "${USER_SYSTEMD_DIR}/${candidate}.service" ]]; then
      printf '%s' "${candidate}"
      return 0
    fi
  done

  mapfile -t candidates < <(find "${USER_SYSTEMD_DIR}" -maxdepth 1 -type f \( -name 'openclaw-gateway*.service' -o -name 'clawdbot-gateway.service' -o -name 'moltbot-gateway.service' \) -printf '%f\n' 2>/dev/null | sed 's/\.service$//' | sort -u)

  if [[ "${#candidates[@]}" -eq 1 ]]; then
    printf '%s' "${candidates[0]}"
    return 0
  fi

  if [[ "${#candidates[@]}" -gt 1 ]]; then
    die "Multiple OpenClaw systemd units were found in ${USER_SYSTEMD_DIR}; rerun with --unit-name"
  fi

  die "No OpenClaw systemd user unit was found in ${USER_SYSTEMD_DIR}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --unit-name)
      UNIT_NAME="$2"
      shift 2
      ;;
    --profile)
      PROFILE="$2"
      shift 2
      ;;
    --user-systemd-dir)
      USER_SYSTEMD_DIR="$2"
      shift 2
      ;;
    --no-reload)
      RELOAD_SYSTEMD=0
      shift
      ;;
    --no-restart)
      RESTART_SERVICE=0
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "Unknown option: $1"
      ;;
  esac
done

[[ "$(uname -s)" == "Linux" ]] || die "OpenClaw systemd hardening is Linux-only."

if [[ "${RELOAD_SYSTEMD}" -eq 1 || "${RESTART_SERVICE}" -eq 1 ]]; then
  require_cmd systemctl
fi

mkdir -p "${USER_SYSTEMD_DIR}"
UNIT_NAME="$(resolve_existing_unit_name)"
UNIT_PATH="${USER_SYSTEMD_DIR}/${UNIT_NAME}.service"
OVERRIDE_DIR="${USER_SYSTEMD_DIR}/${UNIT_NAME}.service.d"
OVERRIDE_PATH="${OVERRIDE_DIR}/override.conf"

[[ -f "${UNIT_PATH}" ]] || die "OpenClaw systemd unit not found: ${UNIT_PATH}"

mkdir -p "${OVERRIDE_DIR}"

log "Writing hardening override for ${UNIT_NAME}.service"
cat >"${OVERRIDE_PATH}" <<EOF
# Generated by Apply-OpenClawSystemdHardening.sh
[Unit]
After=network-online.target
Wants=network-online.target

[Service]
RestartSec=5s
NoNewPrivileges=yes
PrivateTmp=yes
PrivateDevices=yes
ProtectControlGroups=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
ProtectClock=yes
ProtectHostname=yes
LockPersonality=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
SystemCallArchitectures=native
UMask=0077
ProtectProc=invisible
ProcSubset=pid
ProtectSystem=full
EOF

if [[ "${RELOAD_SYSTEMD}" -eq 1 ]]; then
  log "Reloading systemd user daemon"
  systemctl --user daemon-reload
fi

if [[ "${RESTART_SERVICE}" -eq 1 ]]; then
  if systemctl --user is-active --quiet "${UNIT_NAME}.service"; then
    log "Restarting ${UNIT_NAME}.service"
    systemctl --user restart "${UNIT_NAME}.service"
  else
    log "${UNIT_NAME}.service is not active; override written without restart"
  fi
fi

log "Applied hardening override at ${OVERRIDE_PATH}"
